spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tickets_test
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:db/migration

  sql:
    init:
      mode: always
      data-locations: classpath:db/seed/test/data.sql